jobs:
  - ${{ each zivid_version in parameters.zivid_versions }}:
    - ${{ each ros_distro in parameters.ros_distros }}:
      - ${{ each compiler in parameters.compilers }}:
        - job:
          displayName: ${{ format('{0}_{1}_{2}', zivid_version, ros_distro, compiler) }}
          pool:
            vmImage: ubuntu-16.04
          steps:
          - script: CI_TEST_ZIVID_VERSION=${{ zivid_version }}
                    CI_TEST_OS=${{ ros_distro }}
                    CI_TEST_COMPILER=${{ compiler }}
                    ./continuous-integration/run_build_and_test_in_docker.sh
