# See corresponding thesis
optimal_standoff_mm: 181.82
minimum_standoff_mm: 127.27
maximum_standoff_mm: 227.27
theta_max_rad: 0.785398   # Is roughly 45deg
psi_max_rad: 0.785398
K_u: 2.63e-6
alpha_rad: 0.39602      # ca. 22,69deg
fan_angle_rad: 0.53669  # Is roughly 30,75deg
