optimal_standoff_mm: 150
minimum_standoff_mm: 100
maximum_standoff_mm: 200
maximum_deviations:
  theta_rad: 0.78   # Is roughly 45deg
  gamma_rad: 0.78
beam_taille_diameter_mm: 0.1
alpha_rad: 0.524    # Is roughly 30deg
fan_angle_rad: 0.785 # Is roughly 45deg
