rate: 10
controller_list:
  - name: fake_manipulator_controller
    type: interpolate
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_endeffector_controller
    joints:
      []
initial:
  - group: manipulator
    pose:  angled