#manipulator:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Speed
  kinematics_solver_timeout: 0.005
# DEPRECATED: kinematics_solver_attempts: 10
# Not applicable: kinematics_solver_search_resolution: 0.005
