sim_dt: 0.02
port_simulation_synchronizer: 19997
port_hardware_interface: 19998
connection_timeout_ms: 5000

laser_scanner_focus_frame_id: "laser_scanner_focus_frame"
explicit_sync_list:
  - "/update_hw_interface"
#  - "/perform_laser_scan"
